import type { Metadata } from "next";
import { Button } from "@/components/Button";
import { ExperienceTimeline } from "@/components/ExperienceTimeline";
import { Reveal } from "@/components/Reveal";
import { SectionHeader } from "@/components/SectionHeader";
import { SkillsGrid } from "@/components/SkillsGrid";
export const metadata: Metadata = { title: "About", description: "About Thandolwethu Mbatha, Johannesburg-based graphic designer and visual storyteller." };
const education = ["Bachelor of Commerce in Entrepreneurship, 2022–2024, Management College of South Africa (MANCOSA)", "Graphic Design Mentorship Programme, 03/2021–07/2021, Artlab Durban", "National Senior Certificate, 2015–2019, Springs Technical High School"];
export default function AboutPage() {
  return <><section className="bg-[#050505] px-4 pb-20 pt-32 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.24em] text-[#D9FF00]">About the designer</p><h1 className="mt-6 display text-[clamp(4rem,13vw,13rem)] uppercase leading-[.76]">Visual systems with cultural pulse.</h1><Reveal><p className="mt-10 max-w-5xl text-2xl leading-10 text-white/70">Creative and versatile graphic designer experienced in social media graphics, brand and corporate identity, digital assets, and web & e-commerce design. Self-taught and gained experience by working with creative companies, freelance clients, and agencies to deliver visuals that enhance engagement and brand storytelling. Passionate about creating impactful visual identities and building brands.</p></Reveal></div></section>
  <section className="paper-grid bg-[#F4F4F0] px-4 py-24 text-black sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="Philosophy" title="Bold where it matters. Clear everywhere else." copy="The work is shaped by strong typography, functional layouts, disciplined negative space, and visual storytelling that gives each brand a memorable point of view." dark/><div className="grid gap-12 lg:grid-cols-2"><Reveal><h2 className="display text-5xl uppercase">Experience</h2><div className="mt-8"><ExperienceTimeline /></div></Reveal><Reveal><h2 className="display text-5xl uppercase">Education</h2><div className="mt-8 border-t border-black/15">{education.map((item) => <p key={item} className="border-b border-black/15 py-5 text-lg font-semibold">{item}</p>)}</div></Reveal></div></div></section>
  <section className="bg-[#050505] px-4 py-24 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="Skills & tools" title="Identity, digital graphics, web design & retouching"/><SkillsGrid/><Reveal className="mt-10"><Button href="/Thandolwethu-Mbatha-Portfolio.pdf" variant="accent">Download portfolio / CV</Button><p className="mt-3 text-sm text-white/45">Placeholder link: add the PDF to the public folder when ready.</p></Reveal></div></section></>;
}
